### ISSUE TITLE
TinyTds::Error: Adaptive Server connection failed

### ISSUE THREAD

**Issue by monteirobrena** [Azure/azure-sql-database-samples#12]
I'm trying to configure my Rails project with SQL on Azure. I'm using Mac OS X 10.11. But when I run `rake db:migrate` I receive this error TinyTds::Error: Adaptive Server connection failed.

I'm looking for answer in Stackoverflow, too.

http://stackoverflow.com/questions/36484700/rails-and-azure-tinytdserror-adaptive-server-connection-failed

**Comment by meet-bhagdev** [comment]
+Andrea

On Thu, Apr 7, 2016 at 11:56 AM -0700, "Brena Monteiro" <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm trying to configure my Rails project with SQL on Azure. I'm using Mac OS X 10.11. But when I run rake db:migrate I receive this error TinyTds::Error: Adaptive Server connection failed.

I'm looking for answer in Stackoverflow, too.

http://stackoverflow.com/questions/36484700/rails-and-azure-tinytdserror-adaptive-server-connection-failedhttps://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fstackoverflow.com%2fquestions%2f36484700%2frails-and-azure-tinytdserror-adaptive-server-connection-failed&data=01%7c01%7cmeetb%40microsoft.com%7c75104fd7e99f44f0c86d08d35f165411%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=9XjWh7%2f%2bTigSIczghqFKgLaWgyjugCrhzkMXoe28CqQ%3d

##

**Comment by ajlam** [comment]
@monteirobrena Are you able to connect to your Azure SQL Database any tools outside of your Rails app? What happens when you run `rake db::setup`?

**Comment by monteirobrena** [comment]
I fixed it, but I need change my `config/database.yml`.

```
staging:
  adapter: sqlserver
  username: 'username@database'
  password: 'password'
  host: 'db-staging.database.windows.net'
  port: 1433
  database: 'db-staging'
  azure: true
```
